### Simulate
POST http://{{host}}/simulate
Content-Type: application/json

{
  "from": "2022-04-29 03:00",
  "to": "2022-04-29 11:00",
  "figiList": [
    "BBG006L8G4H1",
    "BBG00Y91R9T3",
    "BBG005DXJS36"
  ]
}

### List accounts
GET http://{{host}}/user/accounts
Content-Type: application/json

{
  "token": "",
  "mode": "MARKET"
}

### New User
POST http://{{host}}/user
Content-Type: application/x-www-form-urlencoded

token=&mode=MARKET&accountId=2141863817
