name: Creating Artifacts
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: joschi/setup-jdk@v2
        with:
          java-version: '17'
      - name: Build with Gradle
        run: ./gradlew bootJar
      - name: Get job's artifacts
        uses: actions/upload-artifact@v2
        with:
          name: TinkoffTradeBot
          path: build/libs/TinkoffTradeBot-1.0-SNAPSHOT.jar

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v2
        with:
          name: TinkoffTradeBot
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            build/libs/TinkoffTradeBot.jar
